### ISSUE TITLE
Documentation or wiki or explanations?

### ISSUE THREAD

**Issue by mxxcon** [Zaczero/osm-relatify#23] opened 2023-07-08 23:14 UTC
Hello.
Once I load a bus relation I understand the meaning of the marching path.. That's the selection of the ways to be included in the relation.
But what is the meaning of selecting bus stops on the map and on a big list of bus stops?

Perhaps you could create some documentation for this tool?

Thank you.

**Comment by JesseWeinstein** [comment] 2023-07-09 01:49
There is a labeled screenshot that I found got me over the hump of understanding the interface, here: https://wiki.openstreetmap.org/wiki/File:Relatify_instructions.jpg 

It would be great to have that much more widely linked (i.e. from the interface, and the README here).

And more actual text documentation would be helpful too, of course.

**Comment by mxxcon** [comment] 2023-07-09 01:53
Yes, some of those things I figured out, but then there's also another view of the left panel where it shows all the bus stops in a list and if you click on them it puts a checkmark on it...Don't understand what that is for.

**Comment by JesseWeinstein** [comment] 2023-07-09 01:56
Ah, I hadn't found that feature yet myself! Neat. My guess is that it is intended to help verify stops are correct, but documentation would certainly help.

**Comment by Zaczero** [comment] 2023-07-09 09:43
That interface is simply a route summary. The clicking on stops does not actually do anything, it's just for you, so it's easier to confirm the final route with external sources. You simply mark with checkbox stops which you have confirmed. You can of course completely ignore this step.

**Comment by Zaczero** [comment] 2023-07-09 09:47
> There is a labeled screenshot that I found got me over the hump of understanding the interface, here: https://wiki.openstreetmap.org/wiki/File:Relatify_instructions.jpg
> 
> It would be great to have that much more widely linked (i.e. from the interface, and the README here).
> 
> And more actual text documentation would be helpful too, of course.

I'll put that link somewhere in the README. I think that documentation on the OSM Wiki would be a perfect place, as it would make it very easy for people to contribute. I'll start a new section there but I'll let the community write the documentation for now :-). I'll focus on adding new features with my spare time instead.

**Comment by Zaczero** [comment] 2023-08-19 09:48
The documentation is growing and I added some clarification on the summary page:

![image](https://github.com/Zaczero/osm-relatify/assets/10835147/ca83dc84-f20f-46f0-abf4-365040e00689)

Marking as resolved

**Closed by Zaczero** 2023-08-19 09:48 UTC
Labels: documentation
